RESEARCHERS = {
    "camille": {
        "name": "Dr. Camille Verrier",
        "level": "junior",
        "years_experience": 3,
        "location": "Cayenne, French Guiana 🇬🇫",
        "ecosystem": "Amazonian rainforest ecosystem",
        "subjects": ["oropouche virus", "arbovirus", "Aedes mosquitoes", "field epidemiology"],
        "methods": ["epidemiological surveillance", "field data collection", "entomological analysis"],
        "data_access": ["French Guiana seroprevalence data 2024-2026", "Amazonian Aedes populations"],
    },
    "amadou": {
        "name": "Dr. Amadou Diallo",
        "level": "senior",
        "years_experience": 15,
        "location": "Paris, France 🇫🇷",
        "ecosystem": "Computational modeling laboratory",
        "subjects": ["chikungunya", "viral modeling", "epidemic spread"],
        "methods": ["predictive modeling", "computational simulation", "advanced statistics"],
        "data_access": ["West Africa spread models", "historical chikungunya datasets"],
    },
    "lea": {
        "name": "Dr. Léa Fontaine",
        "level": "senior",
        "years_experience": 12,
        "location": "Paris, France 🇫🇷",
        "ecosystem": "Vaccinology laboratory",
        "subjects": ["Lassa fever", "hemorrhagic fevers", "arenavirus", "vaccines"],
        "methods": ["vaccine engineering", "MOPEVAC platform", "viral vectors"],
        "data_access": ["MOPEVAC platform", "phase 2 clinical trial data"],
    },
    "karim": {
        "name": "Karim Belhadj",
        "level": "junior",
        "years_experience": 2,
        "location": "Dakar, Senegal 🇸🇳",
        "ecosystem": "West Africa field terrain",
        "subjects": ["Lassa fever", "hemorrhagic fevers", "seroprevalence"],
        "methods": ["field surveys", "sample collection", "seroprevalence analysis"],
        "data_access": ["rural Senegal seroprevalence data", "field samples 2025-2026"],
    },
}